{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neos-work.fullname" . }}-auth
  labels:
    {{- include "neos-work.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "authToken is required (or set existingSecret)" .Values.authToken | quote }}
{{- end }}
